#! /bin/bash

# Copyright (c) 2017 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

case $0 in
    */*) dir0=`echo "$0" | sed 's,/[^/]*$,,'` ;;
    *) dir0=./ ;;
esac
. "$dir0/ovs-lib" || exit 1

# 5 minutes by default
RELOAD_TIMEOUT_SECS=300
# 10s sleeps by default
RELOAD_SLEEP_SECS=10
# if you want to override, set the above variables in the following file
if [ -f /etc/default/openvswitch-reload-DO ]; then
    . /etc/default/openvswitch-reload-DO
fi


# ovsdb-server and ovs-vswitchd are stopped in identical ways
ovs_stop() {
    systemctl --job-mode=ignore-dependencies stop "$1"
    # Hack to ensure that sysvinit daemons stop when upgrading to
    # systemd units
    if daemon_is_running "$1"; then
        stop_daemon "$1"
    fi
}

# OVS daemons can take minutes to shutdown (apparently). Abstract out a
# wait for death loop that waits up to RELOAD_TIMEOUT_SECS
wait_for_stopped() {
    pname="$1"
    i=0
    while [[ $i -lt $RELOAD_TIMEOUT_SECS ]]; do
        pgrep -c "$pname" >/dev/null 2>&1
        if [ $? != 0 ]; then
            break
        fi
        ovs_stop $pname
        sleep $RELOAD_SLEEP_SECS
        ((i += RELOAD_SLEEP_SECS))
    done
}


stop_ovsdb() {
    wait_for_stopped 'ovsdb-server'
}

start_ovsdb() {
    systemctl --job-mode=ignore-dependencies start ovsdb-server
}

stop_forwarding() {
    wait_for_stopped 'ovs-vswitchd'
}

start_forwarding() {
    systemctl --job-mode=ignore-dependencies start ovs-vswitchd
}

# this hook runs after we have started OVS back up and restored flows
add_managers() {
    # there appears to be some issue with libvirt and the tap device
    # when we upgrade OVS. Use a hammer rather than a knife to avoid
    # INCI-320 in the future, by bouncing every Droplet's NIC.
    for dom in $(virsh list --name | head -1); do
        for tap in $(virsh domiflist $dom | tail +3 | awk '{print $1}'); do
            virsh domif-getlink $dom $tap | grep -q up
            if [ $? == 0 ]; then
                virsh domif-setlink $dom $tap down
                virsh domif-setlink $dom $tap up
            fi
        done
    done
}

if [ "$1" = "force-reload-kmod" ]; then
    force_reload_kmod
else
    restart
fi

exit 0
