#! /bin/sh

# Copyright (c) 2017 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

case $0 in
    */*) dir0=`echo "$0" | sed 's,/[^/]*$,,'` ;;
    *) dir0=./ ;;
esac
. "$dir0/ovs-lib" || exit 1

# ovsdb-server and ovs-vswitchd are stopped in identical ways
ovs_stop() {
    systemctl --job-mode=ignore-dependencies stop "$1"
    # Hack to ensure that sysvinit daemons stop when upgrading to
    # systemd units
    if daemon_is_running "$1"; then
        stop_daemon "$1"
    fi
    # INCI-320: we have seen a small number of hosts not stop ovs-vswitchd. I
    # am not sure if this is due to ovs-vswitchd being busy, or some other
    # strange issue (on one host, I saw OVS being manually started somewhere).
    # We have not seen this occur with ovsdb-server, but the process should
    # already be stopped at this point, so it should be a no-op
    pkill "$1"
}

# OVS daemons can take minutes to shutdown (apparently). Abstract out a
# wait for death loop that waits up to 15 minutes
wait_for_stopped() {
    pname="$1"
    i=0
    # 30 * 30s = 15m
    while [[ $i < 30 ]]; do
        pgrep -c "$pname"
        if [ $? != 0 ]; then
            break
        fi
        ovs_stop "$pname"
        sleep 30
        $i++
    done
}


stop_ovsdb() {
    wait_for_stopped 'ovsdb-server'
}

start_ovsdb() {
    systemctl --job-mode=ignore-dependencies start ovsdb-server
}

stop_forwarding() {
    wait_for_stopped 'ovs-vswitchd'
}

start_forwarding() {
    systemctl --job-mode=ignore-dependencies start ovs-vswitchd
}

add_managers() {
    :
}

if [ "$1" = "force-reload-kmod" ]; then
    force_reload_kmod
else
    restart
fi

exit 0
